Fix divide-by-zero warning in plugin checks
wp-cli/doctor-command pull request #167
Opened 2022-08-18 20:50 UTC by figureone

Aloha, in WordPress environments with no plugins installed, or multisite environments with only network-activated plugins, the `plugin-deactivated` check will throw a divide-by-zero warning:

```
$ wp doctor check plugin-deactivated
PHP Warning:  Division by zero in /home/ubuntu/.wp-cli/packages/vendor/wp-cli/doctor-command/inc/checks/class-plugin-deactivated.php on line 33
+--------------------+---------+--------------------------------------------------+
| name               | status  | message                                          |
+--------------------+---------+--------------------------------------------------+
| plugin-deactivated | success | Less than 40 percent of plugins are deactivated. |
+--------------------+---------+--------------------------------------------------+
```

Example plugin list:
```
$ wp plugin list
+----------------------------+----------------+-----------+---------+
| name                       | status         | update    | version |
+----------------------------+----------------+-----------+---------+
| advanced-custom-fields-pro | active-network | none      | 5.12.3  |
| classic-editor             | active-network | none      | 1.6.2   |
+----------------------------+----------------+-----------+---------+
```

This pull request explicitly checks that there are more than 0 active/inactive plugins, and also adds the `active-network` status to the count of activated plugins in the `plugin-active-count` and `plugin-deactivated` checks. See the following for a list of valid statuses:
https://developer.wordpress.org/cli/commands/plugin/list/

Thanks!

2022-08-18 20:56 UTC, danielbachhuber requested changes
Thanks for the pull request, @figureone !

Can you add some Behat feature tests so we can make sure the bug doesn't crop up again?

2022-08-18 21:01 UTC, figureone commented
Yeah I can work on that next week!

2022-08-19 00:14 UTC, figureone commented
Got to it early! 

```
$ composer behat -- features/check-plugin-deactivated.feature
$ composer behat -- features/check-plugin-active-count.feature
```

Tests should fail without the PR, and pass with it. Let me know if any tweaks are needed. Cheers

2022-08-19 12:01 UTC, danielbachhuber approved these changes

2022-08-19 12:02 UTC, danielbachhuber commented
Looks great, thanks!

2022-08-19 12:02 UTC, merged